import {bebasNeue, poppins, sourceSans3} from '../ui/fonts.js';
import  "bootstrap/dist/css/bootstrap.min.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bebasNeue.variable} ${poppins.variable} ${sourceSans3.variable} antialiased`}>{children}</body>
    </html>
  )
}
